from django.urls import path
from prog1 import views

urlpatterns = [
    path('', views.home, name='home'),
    path('test', views.test, name='test'),
    path('create-user', views.createPerson, name='user-create'),
    path('list', views.user_list, name='user-list'),
    path('artikel', views.artikel, name='artikel'),
    path('artikel-list', views.ArtikelListView.as_view(), name="artikel-list"),
    path('dokumentieren', views.dok, name="dokumentieren"),
    path('dokumentationen', views.doks, name="dokumentationen"),
    #path('setdokumentation', views.setdokumentation, name="setdokumentation"),

    path('django-dok', views.djangodok, name='django-dok'),
    path('models-dok', views.modelsdok, name='models-dok'),
    path('templates-dok', views.templatesdok, name='templates-dok'),
    path('admin-dok', views.admindok, name='admin-dok'),
    path('api-dok', views.apidok, name='api-dok'),
    path('forms-dok', views.formsdok, name='forms-dok'),
    path('appurl-dok', views.appurldok, name='appurl-dok'),
    path('views-dok', views.viewsdok, name='views-dok'),
    path('settings-dok', views.settingsdok, name='settings-dok'),
    path('haupturl-dok', views.haupturldok, name='haupturl-dok'),
    path('github-dok', views.githubdok, name='github-dok'),
    path('sonstiges-dok', views.sonstigesdok, name='sonstiges-dok'),

    path('django-doks', views.djangodok, name='django-doks'),
    path('models-doks', views.modelsdok, name='models-doks'),
    path('templates-doks', views.templatesdok, name='templates-doks'),
    path('admin-doks', views.admindok, name='admin-doks'),
    path('api-doks', views.apidok, name='api-doks'),
    path('forms-doks', views.formsdok, name='forms-doks'),
    path('appurl-doks', views.appurldok, name='appurl-doks'),
    path('views-doks', views.viewsdok, name='views-doks'),
    path('settings-doks', views.settingsdok, name='settings-doks'),
    path('haupturl-doks', views.haupturldok, name='haupturl-doks'),
    path('github-doks', views.githubdok, name='github-doks'),
    path('sonstiges-doks', views.sonstigesdok, name='sonstiges-doks'),
]