from django.urls import path
from prog1 import views

urlpatterns = [
    path('', views.home, name='home'),
    path('test', views.test, name='test'),
    path('create-user', views.createPerson, name='user-create'),
    path('list', views.user_list, name='user-list'),
    path('artikel', views.artikel, name='artikel'),
    path('artikel-list', views.ArtikelListView.as_view(), name="artikel-list"),
    path('dokumentieren', views.dok, name="dokumentieren"),
    path('dokumentationen', views.doks, name="dokumentationen"),
    #path('setdokumentation', views.setdokumentation, name="setdokumentation"),

    path('django-dok', views.djangodok, name='django-dok'),
    path('models-dok', views.modelsdok, name='models-dok'),
    path('templates-dok', views.templatesdok, name='templates-dok'),
    path('admin-dok', views.admindok, name='admin-dok'),
    path('api-dok', views.apidok, name='api-dok'),
    path('forms-dok', views.formsdok, name='forms-dok'),
    path('appurl-dok', views.appurldok, name='appurl-dok'),
    path('views-dok', views.viewsdok, name='views-dok'),
    path('settings-dok', views.settingsdok, name='settings-dok'),
    path('haupturl-dok', views.haupturldok, name='haupturl-dok'),
    path('github-dok', views.githubdok, name='github-dok'),
    path('sonstiges-dok', views.sonstigesdok, name='sonstiges-dok'),

    path('django-doks', views.djangodoks, name='django-doks'),
    path('models-doks', views.modelsdoks, name='models-doks'),
    path('templates-doks', views.templatesdoks, name='templates-doks'),
    path('admin-doks', views.admindoks, name='admin-doks'),
    path('api-doks', views.apidoks, name='api-doks'),
    path('forms-doks', views.formsdoks, name='forms-doks'),
    path('appurl-doks', views.appurldoks, name='appurl-doks'),
    path('views-doks', views.viewsdoks, name='views-doks'),
    path('settings-doks', views.settingsdoks, name='settings-doks'),
    path('haupturl-doks', views.haupturldoks, name='haupturl-doks'),
    path('github-doks', views.githubdoks, name='github-doks'),
    path('sonstiges-doks', views.sonstigesdoks, name='sonstiges-doks'),

    path('post-django', views.djangopost, name='post-django'),
    path('post-models', views.modelspost, name='post-models'),
    path('post-templates', views.templatespost, name='post-templates'),
    path('post-admin', views.adminpost, name='post-admin'),
    path('post-api', views.apipost, name='post-api'),
    path('post-forms', views.formspost, name='post-forms'),
    path('post-appurl', views.appurlpost, name='post-appurl'),
    path('post-views', views.viewspost, name='post-views'),
    path('post-settings', views.settingspost, name='post-settings'),
    path('post-haupturl', views.haupturlpost, name='post-haupturl'),
    path('post-github', views.githubpost, name='post-github'),
    path('post-sonstiges', views.sonstigespost, name='post-sonstiges'),

]