# Generated by Django 3.2.6 on 2021-08-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haupturlmodel',
            old_name='hauptUrlDok',
            new_name='haupturlDok',
        ),
    ]
