# Generated by Django 3.2.6 on 2021-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0002_rename_person_personmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('artikenummer', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('artikelname', models.CharField(max_length=100)),
                ('artikelbeschreibung', models.CharField(max_length=256)),
                ('lieverantenummer', models.CharField(max_length=18)),
                ('img', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
