# Generated by Django 3.2.6 on 2021-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0003_artikel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djangodokumentation', models.CharField(max_length=500)),
                ('modelsdokumentation', models.CharField(max_length=500)),
                ('templatesdokumentation', models.CharField(max_length=500)),
                ('admindokumentation', models.CharField(max_length=500)),
                ('apidokumentation', models.CharField(max_length=500)),
                ('formsdokumentation', models.CharField(max_length=500)),
                ('appurldokumentation', models.CharField(max_length=500)),
                ('viewsdokumentation', models.CharField(max_length=500)),
                ('settingsdokumentation', models.CharField(max_length=500)),
                ('haupturldokumentation', models.CharField(max_length=500)),
                ('sonstigesdokumentation', models.CharField(max_length=500)),
                ('githubdokumentation', models.CharField(max_length=500)),
            ],
        ),
    ]
