# Generated by Django 3.2.6 on 2021-08-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0004_dokumentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentation',
            name='admindokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='apidokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='appurldokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='djangodokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='formsdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='githubdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='haupturldokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='modelsdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='settingsdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='sonstigesdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='templatesdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='viewsdokumentation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
