# Generated by Django 3.2.6 on 2021-08-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0005_auto_20210811_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dokumentation',
            new_name='DokumentationModel',
        ),
    ]
