# Generated by Django 3.2.6 on 2021-08-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0006_rename_dokumentation_dokumentationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='djangodokumentation',
            new_name='django',
        ),
    ]
