# Generated by Django 3.2.6 on 2021-08-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0007_rename_djangodokumentation_dokumentationmodel_django'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='admindokumentation',
            new_name='admindokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='apidokumentation',
            new_name='apidokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='appurldokumentation',
            new_name='appUrldokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='django',
            new_name='djangodokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='formsdokumentation',
            new_name='formsdokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='githubdokumentation',
            new_name='githubdokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='haupturldokumentation',
            new_name='hauptUrldokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='modelsdokumentation',
            new_name='modelsdokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='settingsdokumentation',
            new_name='settingsdokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='sonstigesdokumentation',
            new_name='sonstigesdokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='templatesdokumentation',
            new_name='templatesdokumation',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='viewsdokumentation',
            new_name='viewsdokumation',
        ),
    ]
