# Generated by Django 3.2.6 on 2021-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0009_auto_20210812_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='admindokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='apidokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='appUrldokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='djangodokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='formsdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='githubdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='hauptUrldokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='modelsdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='settingsdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='sonstigesdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='templatesdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='viewsdokumentation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
