# Generated by Django 3.2.6 on 2021-08-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0012_auto_20210812_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='admindokumentation',
            new_name='adminDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='apidokumentation',
            new_name='apiDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='appUrldokumentation',
            new_name='appUrlDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='djangodokumentation',
            new_name='djangoDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='formsdokumentation',
            new_name='formsDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='githubdokumentation',
            new_name='githubDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='hauptUrldokumentation',
            new_name='hauptUrlDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='modelsdokumentation',
            new_name='modelsDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='settingsdokumentation',
            new_name='settingsDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='sonstigesdokumentation',
            new_name='sonstigesDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='templatesdokumentation',
            new_name='templatesDok',
        ),
        migrations.RenameField(
            model_name='dokumentationmodel',
            old_name='viewsdokumentation',
            new_name='viewsDok',
        ),
    ]
