# Generated by Django 3.2.6 on 2021-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0013_auto_20210812_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='adminDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='apiDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='appUrlDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='djangoDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='formsDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='githubDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='hauptUrlDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='modelsDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='settingsDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='sonstigesDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='templatesDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dokumentationmodel',
            name='viewsDok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
