# Generated by Django 3.2.6 on 2021-08-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0017_auto_20210812_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='adminDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='apiDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='appurlmodel',
            name='appUrlDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='djangomodel',
            name='djangoDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='formsmodel',
            name='formsDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='githubmodel',
            name='githubDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='haupturlmodel',
            name='hauptUrlDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='modelsmodel',
            name='modelsDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='settingsDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sonstigesmodel',
            name='sonstigesDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='templatesmodel',
            name='templatesDok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='viewsmodel',
            name='viewsDok',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
